### ISSUE TITLE
Updating Storybook to the latest crashes the build

### ISSUE THREAD

**Issue by timothymarois** [mitevpi/vuetify-component-lib-template#6] opened 2020-12-21 18:54 UTC
First, nice work! Was looking for something like this for a while. Noticed that storybook had an update and decided to run it. looks like it updated from v5 to v6 and now the build no longer works, reverting back. Figured this should be noted for future work on this. 

edit: also to note, I havent actually made any updates to the repo yet, I just installed this a few minutes ago to begin testing and thats when I noticed this error in build after running an update straight from storybook recommendations that appeared.

**Comment by mitevpi** [comment] 2020-12-21 19:04
Hey there thank you for highlighting this issue! I have been out of the frontend world for a while, but I will add this to my to-do list to investigate. Thanks again for your help in identifying this problem :)

**Comment by timothymarois** [comment] 2020-12-21 19:25
@mitevpi Thanks for getting onto it so quickly! If you've got a few seconds, I would love to pick your brain on a few things regarding re-usablity. If you use slack, I have a workspace here [basephp](https://join.slack.com/t/basephp/shared_invite/zt-5exua1io-jmPqx6wSeoq5ZdHTUS4_LA) otherwise no worries, let me know if you are free for a chat.

**Comment by mitevpi** [comment] 2020-12-28 18:20
I think I have this fixed now. Turns out it was a SCSS issue caused by the Storybook 6.0 migration. It was a bit of a hassle trying to figure out what needs to change exactly, because it turns out the Storybook config files were also renamed in the 6.0 migration - so I was making the right changes in the wrong place for a bit.

Resources Used:
1. [Storybook Migration Guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#to-mainjs-configuration)
2. [Storybook Webpack Config](https://storybook.js.org/docs/react/configure/webpack#examples)
3. [Storybook Issue 11466](https://github.com/storybookjs/storybook/issues/11466)

**Comment by mitevpi** [comment] 2020-12-28 18:21
@timothymarois I do have Slack as well - I'll jump on that workspace that you linked a little later. The holiday schedule is a little hectic for me, but I'm sure we can find a time to connect :)

**Comment by timothymarois** [comment] 2020-12-29 20:57
@mitevpi Oh excellent. Thanks for the fix! 

Yeah anytime you want just hop on Slack, im usually always online.

**Closed** 2020-12-29 21:31 UTC
Labels: bug, dependencies, good first issue
